### ISSUE TITLE
第五章，可能的小问题

### ISSUE THREAD

**Issue by sun-te** [greyli/flask-tutorial#10]
第五章的275行左右，user由数据库读出来后仍然是一个类，可能需要在render_template里面使用`name=user.name`才能够正常显示
```python
@app.route('/')
def index():
    user = User.query.first()  # 读取用户记录
    movies = Movie.query.all()  # 读取所有电影记录
    return render_template('index.html', user=user, movies=movies)
```
或者修改第三章的模板格式？

*第八章*
``login_manager.login_view = 'login'`` #大小写问题？改写为Login

**Comment by greyli** [comment]
感谢反馈！

> 可能需要在render_template里面使用name=user.name才能够正常显示

你说的变化章节中有提到，具体见[这里](https://github.com/greyli/flask-tutorial/blob/master/chapters/c5-database.md#%E5%9C%A8%E4%B8%BB%E9%A1%B5%E8%A7%86%E5%9B%BE%E8%AF%BB%E5%8F%96%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%B0%E5%BD%95)。

> login_manager.login_view = 'login' #大小写问题？改写为Login

我认为这里不需要大写。`login_manager` 对应实例化的扩展类对象，`'login'` 对应实现登陆的视图函数名，两者定义时都是小写。`login_view` 是 Flask-Login 定义的类属性，也是小写。
