### ISSUE TITLE
第10章第108页__init__.py 导入模块问题

### ISSUE THREAD

**Issue by NewDoer** [greyli/flask-tutorial#13]
按书上代码执行测试后，提示User not define
之后尝试在最后导入User和Movie模型类后错误解除
from watchlist.models import User,Movie

不知道是我其他代码输入有误，还是书这里导入遗漏了，还请作者指正。

**Comment by liuhao326** [comment]
[原文](https://github.com/greyli/flask-tutorial/blob/master/chapters/c10-organize.md)指出，为了避免循环依赖（A 导入 B，B 导入 A）而把 load_user() 函数和 inject_user() 函数中使用的模型类在函数内进行导入。
具体可见[\_\_init\_\_.py#L27](https://github.com/greyli/watchlist/blob/dbf3577e547a1bdbae062b0fc2af43c66804f317/watchlist/__init__.py#L27)和[\_\_init\_\_.py#L38](https://github.com/greyli/watchlist/blob/dbf3577e547a1bdbae062b0fc2af43c66804f317/watchlist/__init__.py#L38)
故出现 User not define 的错误可能是因为缺少这两个导入语句。请问是否在这两处正确导入了 User？ @NewDoer
