### ISSUE TITLE
视图函数传参和使用flask.request获取参数的区别？

### ISSUE THREAD

**Issue by crissallan** [greyli/flask-tutorial#14]
hello,
请问，在很多程序中的视图函数中都看到 使用 flask.request来获取参数的值，名称等等操作。但是，也有看到一些是对flask的视图函数进行传参来获取参数的。例如这样：
`
@app.route('/goback/<int:year>')
`
`
def go_back(year):
`
`
    return 'Welcome to %d!' % (2018 - year)
`

这两种有什么区别吗？

**Comment by greyli** [comment]
- 视图函数参数是 URL 变量，也就是 URL 规则里面通过尖括号标记的可变部分，比如 `/users/<username>` 里的 username 部分就是 URL 变量。
- `flask.request` 的各个属性存储了解析后的请求信息，比如 Cookie（`request.cookie`）、查询字符串（`request.args`）、表单数据（`request.form`）等。

**Comment by crissallan** [comment]
> - 视图函数参数是 URL 变量，也就是 URL 规则里面通过尖括号标记的可变部分，比如 `/users/<username>` 里的 username 部分就是 URL 变量。
> 
> - `flask.request` 的各个属性存储了解析后的请求信息，比如 Cookie（`request.cookie`）、查询字符串（`request.args`）、表单数据（`request.form`）等。

那是否意味着通过视图函数传参是不太安全的做法？因为变量都会暴露在url中。需要尽量避免这样的用法吗？

**Comment by greyli** [comment]
> 那是否意味着通过视图函数传参是不太安全的做法？因为变量都会暴露在url中。需要尽量避免这样的用法吗？

并不。一个数据要通过 URL 变量传递还是查询字符串传递亦或是表单数据等方式要取决于你的需要，以及对应的 HTTP 设计初衷（比如查询字符串用来传递用于查询的参数，比如页数，排序等等；URL 变量用来传递 URL 里的可变部分数据，比如用户名、文章名、文章 ID 等等；表单数据/请求主体用来传递用户提交的表单数据）。

**Comment by crissallan** [comment]
> > 那是否意味着通过视图函数传参是不太安全的做法？因为变量都会暴露在url中。需要尽量避免这样的用法吗？
> 
> 并不。一个数据要通过 URL 变量传递还是查询字符串传递亦或是表单数据等方式要取决于你的需要，以及对应的 HTTP 设计初衷（比如查询字符串用来传递用于查询的参数，比如页数，排序等等；URL 变量用来传递 URL 里的可变部分数据，比如用户名、文章名、文章 ID 等等；表单数据/请求主体用来传递用户提交的表单数据）。

好的！大概有个概念了，多谢！
