### ISSUE TITLE
错别字勘误

### ISSUE THREAD

**Issue by 13528080556** [greyli/flask-tutorial#15]
![image](https://user-images.githubusercontent.com/42339097/109264558-22156680-7840-11eb-9251-aa496c4f3c5d.png)
此处文字说明举例404， 实际代码举例说明400

**Comment by greyli** [comment]
谢谢，已[修正](https://github.com/greyli/flask-tutorial/commit/d7cd1920e2d415c06ed786401e3ef6c408e069b6)。
