### ISSUE TITLE
第9章代码报错

### ISSUE THREAD

**Issue by dhzyingz** [greyli/flask-tutorial#16]
第9章第二段代码中有个

**from module_foo import sayhello**

但是没有提到module_foo是什么？所以出现了错误提示 **No module named 'module_foo'**

**Comment by greyli** [comment]
结合上下文，前面说「假设编写了一个函数……」，但是没有要求这个函数要保存到哪个文件，所以下面的 module_foo 指的是你自己创建的那个模块名。已在 https://github.com/greyli/flask-tutorial/commit/013f0dcdcf8ee4d2b806a32f8957c24b693a1fb5 改进，感谢反馈。
