### ISSUE TITLE
导入style.css无效

### ISSUE THREAD

**Issue by GarfieldZhan** [greyli/flask-tutorial#4]
请问：我直接使用<link rel="stylesheet" href="{{ url_for('static',filename="style.css") }}" type="text/css">导入css文件，页面显示效果与教程不一致，但是我建了一个新的文件夹再把css文件放进去之后，使用<link rel="stylesheet" href="{{ url_for('static',filename="css/style.css") }}" type="text/css">引用css文件就好了，这是为什么?

**Comment by greyli** [comment]
估计是你前一个项目 CSS 文件也叫 style.css，内容被缓存了，清除浏览器缓存就行了。

**Comment by greyli** [comment]
长时间无回应，先关闭了。如果问题未解决可以继续评论或重开。
