### ISSUE TITLE
关于最后一章部署上线的一个小遗漏

### ISSUE THREAD

**Issue by hacker0limbo** [greyli/flask-tutorial#8]
在[第 11 章](https://read.helloflask.com/c11-deploy)部署上线中, 其中这样写道:
> 最后安装依赖并执行初始化操作：
> ```bash
> $ pipenv install  # 创建虚拟环境并安装依赖
> $ pipenv shell  # 激活虚拟环境
> $ flask initdb  # 初始化数据库
> $ flask admin  # 创建管理员账户
> ```
这里在 `flask initdb`之后似乎少了`flask forge`这条命令用于生成 movies 数据.

另外, 非常感谢前辈的这一教程, 自己跟着做了一遍并加了一些别的小功能, 可以说受益匪浅学到了非常多, 这是我最后的成果: [demo](https://github.com/hacker0limbo/watchlist)

真的非常感谢前辈的教程, 已经购买了前辈的书, 也打算继续跟进! 谢谢

**Comment by greyli** [comment]
很高兴能帮到你。这里我是这样考虑的：真实部署的话，就相当于程序投入使用了，当然会由程序使用者去创建真实的数据，而不是生成虚拟数据。

**Comment by hacker0limbo** [comment]
> 很高兴能帮到你。这里我是这样考虑的：真实部署的话，就相当于程序投入使用了，当然会由程序使用者去创建真实的数据，而不是生成虚拟数据。

有道理, 是我多虑了!
